spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/revenium
    username: revenium
    password: revenium
  jpa:
    hibernate:
      ddl-auto: none
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:29092

server:
  port: 8080
