# Default configs for containers; can be overridden by environment variables
spring:
  profiles:
    active: local
  application:
    name: revenium
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/revenium}
    username: ${SPRING_DATASOURCE_USERNAME:revenium}
    password: ${SPRING_DATASOURCE_PASSWORD:revenium}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    default-schema: public
    schemas: public
    baseline-on-migrate: true
    table: flyway_schema_history
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis}
      port: ${SPRING_DATA_REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

springdoc:
  swagger-ui:
    path: /docs
  api-docs:
    path: /api-docs

server:
  port: ${SERVER_PORT:8080}

revenium:
  aggregation:
    window-seconds: 30
